import type { CodeSettings } from "@/types";

export const _VERSION = "v1.4.4";

export const _PLAYGROUND_SETTINGS_TAB = {
  VIEW: "View",
  THEME: "Theme",
  MAKEUP: "Makeup",
  DECORATE: "Decorate",
  TEMPLATE: "Template",
} as const;

export const DEFAULT_CODE_SETTINGS: CodeSettings = {
  language: "javascript",
  theme: "dracula",
  background: "linear-gradient(140deg, rgb(207, 47, 152), rgb(106, 61, 236))",
  showBackground: true,
  gradientAngle: 135,
  padding: 30,
  borderRadius: 10,
  frameBorderRadius: 10,
  codeBorderRadius: 10,
  showWindowHeader: true,
  windowHeaderAlign: "left",
  fontFamily: "Fira Code",
  fontSize: 14,
  showTrafficLights: true,
  showTrafficLightsColor: true,
  showFileName: true,
  fileName: "index",
  fileNameOpacity: 0.5,
  fileNameFontWeight: 400,
  fileNameFontSize: 13,
  fileNameAlign: "left",
  showProjectName: false,
  projectName: "",
  projectNameOpacity: 0.5,
  projectNameFontWeight: 400,
  projectNameFontSize: 13,
  exportFormat: "webp",
  width: undefined,
  height: undefined,
  wordWrap: false,
  showCaption: false,
  captionText: "Figure: Sample code snippet",
  captionStyle: "normal",
  captionOpacity: 0.5,
  captionPosition: "bottom",
  showLineNumbers: true,
  lineNumberOpacity: 0.5,
  lineNumberBorder: false,
  lineNumberTextAlign: "center",
  highlights: [],
  watermark: {
    enabled: false,
    type: "text",
    text: "Flashot",
    opacity: 0.1,
    color: "#000000",
    x: 50,
    y: 50,
    rotation: -45,
    fontSize: 48,
    fontWeight: 800,
    imageUrl: "",
    imageWidth: 100,
    imageHeight: 100,
  },
  // Label customization defaults
  showLabel: false,
  labelText: "Created by @username",
  labelAlignment: "center",
  labelOpacity: 0.4,
  labelColor: "#ffffff",
  labelFontSize: 9,
  // Border customization defaults
  borderOffset: 0,
  borderStyle: "solid",
  borderWidth: 2,
  borderOpacity: 1,
  borderColor: "#615465",

  headerGap: 0,
  showHeaderBorder: true,
  headerBorderColor: "#3f3f46",

  imageFilters: {
    grayscale: 0,
    sepia: 0,
    blur: 0,
    brightness: 100,
    contrast: 100,
    saturate: 100,
    hueRotate: 0,
    invert: 0,
  },
};
